version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    restart: always
    container_name: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017
    command: --smallfiles
  app:
    image: springio
    ports: 
    - 8080:8080
    links:
    - mongodb